//! run_report.md generator.

use crate::events::AuditEvent;
use crate::artifacts::ArtifactsManifest;
use chrono::{DateTime, Utc};

pub struct RunReport {
    pub run_id: String,
    pub title: String,
    pub execution_mode: String,
    pub result: String,
    pub start: DateTime<Utc>,
    pub end: DateTime<Utc>,
    pub steps_executed: usize,
    pub cloud_llm_calls: u32,
    pub events: Vec<AuditEvent>,
    pub artifacts: ArtifactsManifest,
    pub top_failures: Vec<FailureSummary>,
    pub diff_summary: Vec<String>,
}

pub struct FailureSummary {
    pub signature: String,
    pub where_: String,
    pub key_lines: Vec<String>,
    pub what_tried: String,
    pub suggested_fix: String,
}

impl RunReport {
    pub fn render(&self) -> String {
        let secs = (self.end - self.start).num_seconds();
        let mut md = format!(
"# ADA Run Report

## Summary
- **Task ID**: {}
- **Title**: {}
- **Execution Mode**: {}
- **Result**: {}
- **Wall Time**: {}s
- **Steps Executed**: {}
- **Cloud LLM Calls**: {}

## Artifacts Produced
",
            self.run_id, self.title, self.execution_mode,
            self.result, secs, self.steps_executed, self.cloud_llm_calls,
        );

        for a in &self.artifacts.entries {
            md.push_str(&format!("- [{}]({}) (sha256: `{}`)\n", a.path, a.path, a.sha256));
        }

        md.push_str("\n## Failure Analytics\n");
        if self.top_failures.is_empty() {
            md.push_str("> [!TIP]\n> No critical failures detected. All execution signatures were within nominal bounds.\n");
        } else {
            for (i, f) in self.top_failures.iter().enumerate() {
                md.push_str(&format!(
                    "\n### [{}] {}\n- **Signature**: `{}`\n- **Retry Count**: {}\n- **Root Cause**: {}\n- **Action Taken**: {}\n",
                    i + 1, f.where_, f.signature, f.key_lines.len(), f.what_tried, f.suggested_fix
                ));
            }
        }

        md.push_str("\n## Diff Summary\n");
        if self.diff_summary.is_empty() {
            md.push_str("- No filesystem changes recorded in this run.\n");
        } else {
            for d in &self.diff_summary {
                md.push_str(&format!("- {d}\n"));
            }
        }

        md.push_str("\n---\n*Report generated by Aether Auditing Engine (Phase 07)*\n");
        md
    }
}
